This notebook contain exercises for classes copied form readme.

In [1]:
import numpy as np

## Exercise 1 

Fix the code, so that all ``assert`` pass.

In [10]:
arr1 = []
arr2 = []
assert len(arr1) == 0
assert len(arr2) == 0
assert np.all(arr1 != 100)
assert np.all(arr2 != 156)
assert np.all(arr1 + arr2 != 0)

## Exercise 2

Load data from ``data/sample.csv``; calculate mean, median and std for each column separately.
Solve this using numpy and without numpy (or pandas etc.)

Measure the time of it execution (using ``%time`` magic or ``time()`` function from ``time`` module) for each case.

In [20]:
import pandas as pd
df = pd.read_csv('data/sample.csv', sep=' ', header=None)

In [23]:
%%time
df.describe()

CPU times: user 23.4 ms, sys: 127 µs, total: 23.6 ms
Wall time: 21 ms


0           1           2           3           4           5  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     4.950237    5.105682    6.335521    7.135616    6.165667    8.007182   
std      3.052706    3.136568    3.554310    3.823819    3.818811    3.984624   
min      0.175005    0.154478    0.030807    0.440015    0.379266    0.374968   
25%      2.098424    2.220032    4.016421    3.703633    2.697510    4.666823   
50%      4.628460    5.007021    6.416916    7.546434    6.384272    8.227743   
75%      7.644819    7.371599    9.410600   10.468933    8.845840   10.774935   
max      9.904395   10.991941   11.813727   12.943929   13.977270   14.971221   

                6           7           8           9  
count  100.000000  100.000000  100.000000  100.000000  
mean     7.155125    7.671688    9.486200    8.626120  
std      4.640116    4.768114    4.949590    5.552116  
min      0.000961    0.067342    0.295102    0.053400  
25%      2.788796    4.292928    5.394147    4.146556  
50%      6.596736    6.976809    9.433469    8.580686  
75%     11.119779   10.866891   13.866383   13.486865  
max     15.967929   16.841476   17.996654   18.992390

In [26]:
%%time
for col in df.columns:
    print(f'Column {col}: mean: {df[col].mean():.4f}, median: {df[col].median():.4f}, std {df[col].std():.4f}')

Column 0: mean: 4.9502, median: 4.6285, std 3.0527
Column 1: mean: 5.1057, median: 5.0070, std 3.1366
Column 2: mean: 6.3355, median: 6.4169, std 3.5543
Column 3: mean: 7.1356, median: 7.5464, std 3.8238
Column 4: mean: 6.1657, median: 6.3843, std 3.8188
Column 5: mean: 8.0072, median: 8.2277, std 3.9846
Column 6: mean: 7.1551, median: 6.5967, std 4.6401
Column 7: mean: 7.6717, median: 6.9768, std 4.7681
Column 8: mean: 9.4862, median: 9.4335, std 4.9496
Column 9: mean: 8.6261, median: 8.5807, std 5.5521
CPU times: user 7.1 ms, sys: 69 µs, total: 7.16 ms
Wall time: 5.05 ms


## Exercise 3

Load data from ``data/ex3_data.npy`` and filter out rows with ``nan`` values.
Report how many rows are dropped during filtration, globally and how many ``nan`` are in each column.

In [35]:
data3 = np.load('data/ex3_data.npy')

In [53]:
data3_nonan = data3[np.isnan(data3).any(axis=1)]

no_nan_rows = data3_nonan.shape[0]

no_nan_cols = data3[:,np.isnan(data3).any(axis=0)].shape[1]

In [54]:
print(f'Number of dropped rows (with NaN): {no_nan_rows}. Number of columns with NaN: {no_nan_cols}')

Number of dropped rows (with NaN): 10. Number of columns with NaN: 4


In [56]:
np.isnan(data3).sum(axis=0)

array([3, 3, 4, 1])

## Exercise 4

Load data from ``data/iris.csv`` using ``loadtxt`` from ``numpy``. 
Skip header and name columns.
For each column calculate: `mean`, `median` and `std` using `axis` parameter.

In [101]:
iris_data = np.loadtxt('data/iris.csv', skiprows=1, usecols=[0,1,2,3], delimiter=',')

In [103]:
iris_data.mean(axis=0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [106]:
np.median(iris_data, axis=0)

array([5.8 , 3.  , 4.35, 1.3 ])

In [105]:
iris_data.std(axis=0)

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

## Exercise 5

Load data from ``data/sample_treated.npz``. 
Assume that each row of the ``outputs`` array contains information about the size of some structure traced in time.
We would like to know which object grows doubles its size during observation.


In [78]:
data5 = np.load('data/sample_treated.npz')
outputs = data5['outputs']

In [84]:
for i in range(outputs.shape[0]-1):
    if np.array_equal(outputs[i+1], 2*outputs[i]):
        print(outputs[i])